<template>
    <section>
        <div class="title">
            <span class="shop-title">Regulamin</span>
            <h2>Płatności</h2>
            <hr/>
        </div>
        <div class="reg">
            <p>1. DEFINICJE </p>
            <p>1.1 LAKE-LAND.pl - PRYWATNY SERWER GRY KOMPUTEROWEJ MINECRAFT UDSTĘPNIONY INNYM GRACZOM W INTERNECIE ORAZ STRONA INTERNETOWA O ADRESIE HTTP://LAKE-LAND.PL</p>
            <p>1.2 HOTPAY - HTTPS://HOTPAY.PL - INTERNETOWY SERWIS USŁUGOWY, W KTÓRYM KLIENT MOŻE DOKONAĆ PŁATNOŚCI NA RZECZ DOMENA.PL ZA POŚREDNICTWEM STRONY INTERNETOWEJ.</p>
            <p>1.3 USŁUGA - UDOSTĘPNIENIE UŻYTKOWNIKOWI UPRAWNIEŃ/DODATKOWYCH MOŻLIWOŚCI NA SERWERZE DOMENA.PL DO KONTA GRACZA.</p> 
            <p>1.4 SKLEP - PODSTRONA INTERNETOWA UMIESZCZONA NA STRONIE INTERNETOWEJ DOMENA.PL, NA KTÓREJ KLIENT MOŻE DOKONAĆ PŁATNOŚCI.</p>
            <p>1.5 PŁATNOŚĆ SPEŁNIENIE PRZEZ KLIENTA NA RZECZ TWOCASTLE.PL ŚWIADCZENIA PIENIĘŻNEGO ZA POŚREDNICTWEM HOTPAY POPRZEZ WYBRANĄ METODĘ PŁATNOŚCI.</p>
            <p>1.6 GRACZ/UŻYTKOWNIK - OSOBA FIZYCZNA LUB PRAWNA UŻYTKUJĄCA SERWERY DOMENA.PL.</p>
            <p>1.7 KLIENT - OSOBA FIZYCZNA, PRAWNA LUB JEDNOSTKA ORGANIZACYJNA, KTÓRA DOKONUJE ZAKUPU TOWARÓW LUB NABYWA USŁUGI W SKLEPIE I Z TEGO TYTUŁU DOKONUJE PŁATNOŚCI</p>
            <p>1.8 BAN - POZBAWIENIE GRACZA MOŻLIWOŚCI WEJŚCIA NA WSZYSTKIE SERWERY DOMENA.PL ŁĄCZNIE Z LOBBY ZA NIEPRZESTRZEGANIE REGULAMINÓW.</p>
            <p>1.9 NOWA EDYCJA - USUNIĘCIE, A NASTĘPNIE UTWORZENIE NA NOWO POSZCZEGÓLNEGO PODSERWERA WRAZ Z USUNIĘCIEM Z NIEGO WSZYSTKICH PRZEDMIOTÓW/BUDOWLI/ZAWARTOŚCI EKWIPUNKÓW GRACZY ORAZ USŁUG ZAKUPIONYCH PRZEZ GRACZY.</p>
            <p>2. INFORMACJE OGÓLNE</p>
            <p>2.1 WŁAŚCICIEL STRONY I SKLEPU ZASTRZEGA SOBIE PRAWO DO ZMIANY PONIŻSZEGO REGULAMINU W DOWOLNYM MOMENCIE.</p>
            <p>2.2 WŁAŚCICIEL STRONY I SKLEPU ZASTRZEGA SOBIE PEŁNE PRAWO DO ZMIAN W PROWADZONYCH USŁUGACH ORAZ CENACH USŁUG ŚWIADCZONYCH PRZEZ DOMENA.PL.</p>
            <p>2.3 UŻYTKOWNIK, POSIADAJĄC KONTO NA SERWERZE DOMENA.PL, AKCEPTUJE WARUNKI REGULAMINU WEWNĘTRZNEGO SERWERA DOMENA.PL.</p> 
            <p>2.4 REKLAMACJE W ZWIĄZKU Z DZIAŁANIEM DOMENA.PL ZGŁASZAĆ NALEŻY POPRZEZ PROGRAM DISCORD POD ADRESEM DC.DOMENA.PL PROSIMY O SZCZEGÓLNE ZWRÓCENIE UWAGI NA POPRAWNOŚĆ WPISYWANEGO INFORMACJI, GDYŻ ZASTRZEGAMY SOBIE PRAWO DO BRAKU ODPOWIEDZI NA REKLAMACJĘ W PRZYPADKU BRAKU PODANIA LUB PODANIA NIEPRAWIDŁOWYCH INFORMACJI. ZAKUPIONY TOWAR MOŻNA ZWRÓCIĆ W CIĄGU 7 DNI OD DATY JEGO OTRZYMANIA.</p>
            <p>3. ZASADY ŚWIADCZENIA USŁUG:</p>
            <p>3.1 WŁAŚCICIEL STRONY I SKLEPU ORAZ FIRMA OBSŁUGUJĄCA PŁATNOŚCI NIE PONOSI ODPOWIEDZIALNOŚCI ZA BŁĘDY POPEŁNIONE PRZEZ KLIENTA W TRAKCIE UŻYTKOWANIA SKLEPU.</p>
            <p>3.2 W PRZYPADKU OTRZYMANIA BANA KLIENTOWI NIE PRZYSŁUGUJE ZWROT KOSZTÓW ZAKUPU.</p>
            <p>3.3 WSZYSTKIE WIRTUALNE BUDOWLE ORAZ POMYSŁY WYKORZYSTANE NA SERWERZE / DLA SERWERA LUB AKTUALNIE SĄ UŻYWANE NA SERWERZE SĄ WŁASNOŚCIĄ SERWERA I NIKOMU, KTO TWORZYŁ TĄ ZAWARTOŚĆ, NIE PRZYSŁUGUJĄ ZWROTY / REKOMPENSATY.</p>
            <p>3.4 KAŻDY UŻYTKOWNIK SERWERA JEST OBOWIĄZANY DO ZAPOZNANIA SIĘ Z NINIEJSZYM REGULAMINEM I STOSOWANIA SIĘ DO PRZEWIDZIANYCH W NIM REGULACJI.</p>
            <p>3.5 WŁAŚCICIEL SERWISU: KAMIL KŁUSEK, ADRES: JURCZYŃSKIEGO 10, MIASTO: 92-306 ŁÓDŹ, TELEFON: (+48) 516607200, EMAIL: KONTAKT.TWOCASTLE@GMAIL.COM</p>
        </div>
        <div class="title">
            <span class="shop-title">Polityka</span>
            <h2>Prywatności</h2>
            <hr/>
        </div>
        <div class="reg">
            <p>nA PODSTAWIE ART. 13 UST. 1 I UST. 2 ROZPORZĄDZENIA PARLAMENTU EUROPEJSKIEGO I RADY (UE) 2016/679 Z 27 KWIETNIA 2016 R. W SPRAWIE OCHRONY OSÓB FIZYCZNYCH W ZWIĄZKU Z PRZETWARZANIEM DANYCH OSOBOWYCH I W SPRAWIE SWOBODNEGO PRZEPŁYWU TYCH DANYCH ORAZ UCHYLENIA DYREKTYWY 95/46/WE (OGÓLNE ROZPORZĄDZENIE O OCHRONIE DANYCH OSOBOWYCH NAZYWANEJ: „RODO”, INFORMUJEMY O SPOSOBIE PRZETWARZANIA DANYCH OSOBOWYCH NA NASZYM SERWISIE.</p>
            <p>INFORMACJE OGÓLNE</p>
            <p>1. NINIEJSZA POLITYKA DOTYCZY SERWISU WWW,SERWERÓW GIER, FUNKCJONUJĄCEGO POD ADRESEM URL: TWOCASTLE.PL</p>
            <p>2. ADRES KONTAKTOWY POCZTY ELEKTRONICZNEJ OPERATORA: KONTAKT@TWOCASTLE.PL</p>
            <p>3. WŁAŚCICIELEM SERWISU WWW.TWOCASTLE.PL JEST KAMIL KŁUSEK MIESZKAJĄCY W MIEŚCIE ŁÓDŹ POD ADRESEM JURCZYŃSKIEGO 10/13 92-306.</p>
            <p>4. SERWIS ZBIERA INFORMACJE PODANE DOBROWOLNIE PRZEZ UŻYTKOWNIKA LUB POPRZEZ ZAPISYWANIE W URZĄDZENIACH KOŃCOWYCH PLIKÓW COOKIE (TZW. „CIASTECZKA”).</p>
            <p>5. SERWIS WYKORZYSTUJE DANE OSOBOWE W NASTĘPUJĄCYCH CELACH:</p>
            <p>- REALIZACJA ZAMÓWIONYCH USŁUG</p>
            <p>- PREZENTACJA OFERTY LUB INFORMACJI</p>
            <p>6. SERWIS MOŻE ZAPISAĆ INFORMACJE O PARAMETRACH POŁĄCZENIA (ADRES IP, ADRES E-MAIL, HISTORIA ZAKUPÓW W SKLEPIE TWOCASTLE.PL, CZAS)</p>
            <p>7. ADMINISTRATOR MA PRAWO PRZEKAZYWAĆ TWOJE DANE OSOBOWE OSOBOM TRZECIM W CELU WYPEŁNIENIA OBOWIĄZKÓW.</p>
            <p>DOTYCZY TO:</p>
            <p>- ORGANÓW ŚCIGANIA</p>
            <p>- KANCELARII PRAWNYCH I WINDYKATORÓW</p>
            <p>- OPERATORÓW PŁATNOŚCI</p>
            <p>DŁUGOŚĆ PRZECHOWYWANYCH DANYCH</p>
            <p>1. DANE ZE STRONY HTTPS://TWOCASTLE.PL/ BĘDĄ PRZECHOWYWANE DO 3 LAT.</p>
            <p>2. DANE Z SERWERÓW GIERBĘDĄ PRZECHOWYWANE DOPÓKI TWOJE KONTO NA SERWERZE BĘDZIE AKTYWNE/ZAREJESTROWANE.</p>
            <p>3. LOGI Z SERWERÓW GIER BĘDĄ PRZECHOWYWANE PRZEZ 31 DNI.</p>
            <p>4. LOGI Z SERWERA DISCORD BĘDĄ PRZECHOWYWANE DO MOMENTU ZAMKNIĘCIA SERWERA DISCORD.</p>
            <p>JAKIE DANE ZBIERAJĄ SERWERY GIER</p>
            <p>1. SERWERY GIER ZBIERAJĄ NASTĘPUJĄCE DANE:</p>
            <p>- ADRESY IP (W CELU AUTOMATYZACJI LOGOWANIA, PRZECIWDZIAŁANIU NADUŻYCIOM LOGOWANIA),</p>
            <p>- NAZWY GRACZA ORAZ JEGO UUID,</p>
            <p>- WSZYSTKIE WIADOMOŚCI Z CZATU OGÓLNEGO GRY,</p>
            <p>- WSZYSTKIE WIADOMOŚCI Z CZATÓW PRYWATNYCH,</p>
            <p>- WSZELKIE INTERAKCJE GRACZA NA SERWERZE GIER NP. POSTAWIONE BLOKI, ZNISZCZONE BLOKI, NAPISANE TABLICZKI,</p>
            <p>- AKTYWNOŚĆ / CZAS POŁĄCZENIA GRACZA Z SERWEREM.</p>
            <p>WYBRANE METODY OCHRONY DANYCH STOSOWANE PRZEZ OPERATORA</p> 
            <p>1. MIEJSCA LOGOWANIA I WPROWADZANIA DANYCH OSOBOWYCH SĄ CHRONIONE W WARSTWIE TRANSMISJI (CERTYFIKAT SSL). DZIĘKI TEMU DANE OSOBOWE I DANE LOGOWANIA, WPROWADZONE NA STRONIE, ZOSTAJĄ ZASZYFROWANE W KOMPUTERZE UŻYTKOWNIKA I MOGĄ BYĆ ODCZYTANE JEDYNIE NA DOCELOWYM SERWERZE.</p>
            <p>2. HASŁA UŻYTKOWNIKÓW SĄ PRZECHOWYWANE W POSTACI HASHOWANEJ. FUNKCJA HASHUJĄCA DZIAŁA JEDNOKIERUNKOWO - NIE JEST MOŻLIWE ODWRÓCENIE JEJ DZIAŁANIA, CO STANOWI OBECNIE WSPÓŁCZESNY STANDARD W ZAKRESIE PRZECHOWYWANIA HASEŁ UŻYTKOWNIKÓW.</p>
            <p>3. OPERATOR OKRESOWO ZMIENIA SWOJE HASŁA ADMINISTRACYJNE. W CELU OCHRONY DANYCH OPERATOR REGULARNIE WYKONUJE KOPIE BEZPIECZEŃSTWA.</p>
            <p>4. ISTOTNYM ELEMENTEM OCHRONY DANYCH JEST REGULARNA AKTUALIZACJA WSZELKIEGO OPROGRAMOWANIA, WYKORZYSTYWANEGO PRZEZ OPERATORA DO PRZETWARZANIA DANYCH OSOBOWYCH, CO W SZCZEGÓLNOŚCI OZNACZA REGULARNE AKTUALIZACJE KOMPONENTÓW PROGRAMISTYCZNYCH.</p>
            <p>INFORMACJE W FORMULARZACH</p>
            <p>1. SERWIS ZBIERA INFORMACJE PODANE DOBROWOLNIE PRZEZ UŻYTKOWNIKA, W TYM DANE OSOBOWE, O ILE ZOSTANĄ ONE PODANE.</p>
            <p>2. SERWIS MOŻE ZAPISAĆ INFORMACJE O PARAMETRACH POŁĄCZENIA (OZNACZENIE CZASU, ADRES IP).</p>
            <p>3. SERWIS, W NIEKTÓRYCH WYPADKACH, MOŻE ZAPISAĆ INFORMACJĘ UŁATWIAJĄCĄ POWIĄZANIE DANYCH W FORMULARZU Z ADRESEM E-MAIL UŻYTKOWNIKA WYPEŁNIAJĄCEGO FORMULARZ. W TAKIM WYPADKU ADRES E-MAIL UŻYTKOWNIKA POJAWIA SIĘ WEWNĄTRZ ADRESU URL STRONY ZAWIERAJĄCEJ FORMULARZ.</p>
            <p>4. DANE PODANE W FORMULARZU SĄ PRZETWARZANE W CELU WYNIKAJĄCYM Z FUNKCJI KONKRETNEGO FORMULARZA, NP. W CELU DOKONANIA PROCESU OBSŁUGI ZGŁOSZENIA SERWISOWEGO LUB KONTAKTU HANDLOWEGO, REJESTRACJI USŁUG ITP. KAŻDORAZOWO KONTEKST I OPIS FORMULARZA W CZYTELNY SPOSÓB INFORMUJE, DO CZEGO ON SŁUŻY.</p>
            <p>LOGI ADMINISTRATORA</p>
            <p>1. INFORMACJE ZACHOWANIU UŻYTKOWNIKÓW W SERWISIE MOGĄ PODLEGAĆ LOGOWANIU. DANE TE SĄ WYKORZYSTYWANE W CELU ADMINISTROWANIA SERWISEM.</p>
            <p>ISTOTNE TECHNIKI MARKETINGOWE</p>
            <p>1. OPERATOR STOSUJE ANALIZĘ STATYSTYCZNĄ RUCHU NA STRONIE, POPRZEZ GOOGLE ANALYTICS (GOOGLE INC. Z SIEDZIBĄ W USA). OPERATOR NIE PRZEKAZUJE DO OPERATORA TEJ USŁUGI DANYCH OSOBOWYCH, A JEDYNIE ZANONIMIZOWANE INFORMACJE. USŁUGA BAZUJE NA WYKORZYSTANIU CIASTECZEK W URZĄDZENIU KOŃCOWYM UŻYTKOWNIKA. W ZAKRESIE INFORMACJI O PREFERENCJACH UŻYTKOWNIKA GROMADZONYCH PRZEZ SIEĆ REKLAMOWĄ GOOGLE UŻYTKOWNIK MOŻE PRZEGLĄDAĆ I EDYTOWAĆ INFORMACJE WYNIKAJĄCE Z PLIKÓW COOKIES PRZY POMOCY NARZĘDZIA: HTTPS://WWW.GOOGLE.COM/ADS/PREFERENCES/</p>
            <p>INFORMACJA O PLIKACH COOKIES</p>
            <p>1. SERWIS KORZYSTA Z PLIKÓW COOKIES.</p>
            <p>2. PLIKI COOKIES (TZW. „CIASTECZKA”) STANOWIĄ DANE INFORMATYCZNE, W SZCZEGÓLNOŚCI PLIKI TEKSTOWE, KTÓRE PRZECHOWYWANE SĄ W URZĄDZENIU KOŃCOWYM UŻYTKOWNIKA SERWISU I PRZEZNACZONE SĄ DO KORZYSTANIA ZE STRON INTERNETOWYCH SERWISU. COOKIES ZAZWYCZAJ ZAWIERAJĄ NAZWĘ STRONY INTERNETOWEJ, Z KTÓREJ POCHODZĄ, CZAS PRZECHOWYWANIA ICH NA URZĄDZENIU KOŃCOWYM ORAZ UNIKALNY NUMER.</p>
            <p>3. PODMIOTEM ZAMIESZCZAJĄCYM NA URZĄDZENIU KOŃCOWYM UŻYTKOWNIKA SERWISU PLIKI COOKIES ORAZ UZYSKUJĄCYM DO NICH DOSTĘP JEST OPERATOR SERWISU.</p>
            <p>4. PLIKI COOKIES WYKORZYSTYWANE SĄ W NASTĘPUJĄCYCH CELACH:</p>
            <p>- UTRZYMANIE SESJI UŻYTKOWNIKA SERWISU (PO ZALOGOWANIU), DZIĘKI KTÓREJ UŻYTKOWNIK NIE MUSI NA KAŻDEJ PODSTRONIE SERWISU PONOWNIE WPISYWAĆ LOGINU I HASŁA;</p>
            <p>- REALIZACJI CELÓW OKREŚLONYCH POWYŻEJ W CZĘŚCI "ISTOTNE TECHNIKI MARKETINGOWE";</p>
            <p>5. W RAMACH SERWISU STOSOWANE SĄ DWA ZASADNICZE RODZAJE PLIKÓW COOKIES: „SESYJNE” (SESSION COOKIES) ORAZ „STAŁE” (PERSISTENT COOKIES). COOKIES „SESYJNE” SĄ PLIKAMI TYMCZASOWYMI, KTÓRE PRZECHOWYWANE SĄ W URZĄDZENIU KOŃCOWYM UŻYTKOWNIKA DO CZASU WYLOGOWANIA, OPUSZCZENIA STRONY INTERNETOWEJ LUB WYŁĄCZENIA OPROGRAMOWANIA (PRZEGLĄDARKI INTERNETOWEJ). „STAŁE” PLIKI COOKIES PRZECHOWYWANE SĄ W URZĄDZENIU KOŃCOWYM UŻYTKOWNIKA PRZEZ CZAS OKREŚLONY W PARAMETRACH PLIKÓW COOKIES LUB DO CZASU ICH USUNIĘCIA PRZEZ UŻYTKOWNIKA.</p>
            <p>6. OPROGRAMOWANIE DO PRZEGLĄDANIA STRON INTERNETOWYCH (PRZEGLĄDARKA INTERNETOWA) ZAZWYCZAJ DOMYŚLNIE DOPUSZCZA PRZECHOWYWANIE PLIKÓW COOKIES W URZĄDZENIU KOŃCOWYM UŻYTKOWNIKA. UŻYTKOWNICY SERWISU MOGĄ DOKONAĆ ZMIANY USTAWIEŃ W TYM ZAKRESIE. PRZEGLĄDARKA INTERNETOWA UMOŻLIWIA USUNIĘCIE PLIKÓW COOKIES. MOŻLIWE JEST TAKŻE AUTOMATYCZNE BLOKOWANIE PLIKÓW COOKIES SZCZEGÓŁOWE INFORMACJE NA TEN TEMAT ZAWIERA POMOC LUB DOKUMENTACJA PRZEGLĄDARKI INTERNETOWEJ.</p>
            <p>7. OGRANICZENIA STOSOWANIA PLIKÓW COOKIES MOGĄ WPŁYNĄĆ NA NIEKTÓRE FUNKCJONALNOŚCI DOSTĘPNE NA STRONACH INTERNETOWYCH SERWISU.</p>
            <p>>8. PLIKI COOKIES ZAMIESZCZANE W URZĄDZENIU KOŃCOWYM UŻYTKOWNIKA SERWISU WYKORZYSTYWANE MOGĄ BYĆ RÓWNIEŻ PRZEZ WSPÓŁPRACUJĄCE Z OPERATOREM SERWISU PODMIOTY, W SZCZEGÓLNOŚCI DOTYCZY TO FIRM: GOOGLE (GOOGLE INC. Z SIEDZIBĄ W USA), FACEBOOK (FACEBOOK INC. Z SIEDZIBĄ W USA), TWITTER (TWITTER INC. Z SIEDZIBĄ W USA).</p>
            <p>ZARZĄDZANIE PLIKAMI COOKIES – JAK W PRAKTYCE WYRAŻAĆ I COFAĆ ZGODĘ?</p>
            <p>1. JEŚLI UŻYTKOWNIK NIE CHCE OTRZYMYWAĆ PLIKÓW COOKIES, MOŻE ZMIENIĆ USTAWIENIA PRZEGLĄDARKI. ZASTRZEGAMY, ŻE WYŁĄCZENIE OBSŁUGI PLIKÓW COOKIES NIEZBĘDNYCH DLA PROCESÓW UWIERZYTELNIANIA, BEZPIECZEŃSTWA, UTRZYMANIA PREFERENCJI UŻYTKOWNIKA MOŻE UTRUDNIĆ, A W SKRAJNYCH PRZYPADKACH MOŻE UNIEMOŻLIWIĆ KORZYSTANIE ZE STRON WWW.</p>
            <p>2. W CELU ZARZĄDZANIA USTAWIENIA COOKIES WYBIERZ Z LISTY PONIŻEJ PRZEGLĄDARKĘ INTERNETOWĄ, KTÓREJ UŻYWASZ I POSTĘPUJ ZGODNIE Z INSTRUKCJAMI:</p>
            <p>- EDGE</p>
            <p>- INTERNET EXPLORER</p>
            <p>- CHROME</p>
            <p>- SAFARI</p>
            <p>- FIREFOX</p>
            <p>- OPERA</p>

            <p>uRZĄDZENIA MOBILNE:</p>
            <p>-ANDROID</p>
            <p>- SAFARI (IOS)</p>
            <p>- WINDOWS PHONE</p>
            <p>REZYGNACJA Z PRZECHOWYWANIA DANYCH</p>
            <p>1. UŻYTKOWNIK MOŻE DOBROWOLNIE ZREZYGNOWAĆ Z PRZECHOWYWANIA JEGO DANYCH PRZEZ SERWIS. W TYM CELU NALEŻY WYSŁAĆ MAIL REZYGNACYJNY NA ADRES: KONTAKT@TWOCASTLE.PL, W KTÓRYM ZAMIEŚCIMY WSZYSTKIE DANE NIEZBĘDNE DO WERYFIKACJI ZGŁOSZENIA.</p>
        </div>
        <!-- <div class="reg">
            <p>§1 Właścicielem serwisu jest Jeremiasz Czudec zamieszkały w Nosówka prowadzący nie zarejestrowaną działalność gospodarczą oraz sklep lake-land.pl</p>
            <p>§3 Serwis polega na udostępnieniu infrastruktury technicznej SMS Premium do dodania ogłoszenia płatnego w serwisie lokalnym lake-land.pl</p>
            <p>§4 Koszt wysłania SMS wynosi: 
            - 71480 1zł zł netto (1,23 zł brutto). 
            - 72480 2 zł netto (2,46 zł brutto). 
            - 73480 3 zł netto (3,69 zł brutto). 
            - 74480 4 zł netto (4,92 zł brutto). 
            - 75480 5 zł netto (6,15 zł brutto). 
            - 76480 6 zł netto (7,38 zł brutto). 
            - 79480 9 zł netto (11,07 zł brutto). 
            - 91400 14 zł netto (17,22 zł brutto). 
            - 91900 19 zł netto (23,37 zł brutto). 
            - 91900 20 zł netto (24,70 zł brutto). 
            - 91900 25 zł netto (30,75 zł brutto). 
            Usługa dostępna jest dla sieci Orange, T-Mobile, Plus, Play, Sferia, Cyfrowy Polsat oraz wszystkich sieci wirtualnych MVNO (np. GaduAir, mBank mobile, Aster). 
            </p>
            <p>§5 Tylko poprawnie wysłany SMS z dokładnie wpisaną komendą i numerem Premium, uprawnia do uzyskania kodu jednorazowego. W przypadku błędnie wpisanego SMSa, Użytkownik otrzyma komunikat o błędnie wysłanej komendzie. Zgodnie z zasadami opłata za każdego wysłanego SMSa jest pobierana przezoperatorów GSM w momencie jego wysłania, nawet jeśli jest to nieprawidłowy SMS. Organizator informuje, iż nie ma obowiązku zwrotu kosztów SMSa bądź przesłania ponownie kodu, w przypadku jeśli Użytkownik wysłał błędną treść SMSa.</p>
            <p>§6 Użytkownikowi przysługuje prawo złożenia reklamacji związanej z funkcjonowaniem Serwisu, bądź nieotrzymania SMSa z kodem, mimo wysłania prawidłowej treści SMS, w terminie 7 dni od dnia wystąpienia zdarzenia będącego przyczyną reklamacji poprzez wysłanie e-maila na adres: lake-land-sup@gmail.com</p>
            <p>§7 Organizator nie ponosi odpowiedzialności za wiadomości przesłane przez Uczestnika w formie SMS nie dostarczone lub opóźnione z przyczyn leżących po stronie Operatora sieci komórkowej.</p>
        </div> -->
    </section>
</template>


<style scoped src="@/assets/style/views/rules.less" lang="less"></style>